# Generated by Django 5.1.3 on 2024-11-25 22:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('second_name', models.CharField(default='', max_length=50)),
                ('telefono', models.CharField(default='', max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_usuario', models.CharField(choices=[('P', 'Propietario'), ('A', 'Arrendatario')], default='A', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
