# Generated by Django 5.1.3 on 2024-12-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
