# Generated by Django 5.1.3 on 2024-11-25 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0002_rename_precio_mensual_inmueble_precio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inmueble',
            name='user',
        ),
        migrations.AddField(
            model_name='inmueble',
            name='nombre_inmueble',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
