# Generated by Django 5.1.3 on 2024-11-20 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0002_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('ARRENDADOR', 'Arrendador'), ('ARRENDATARIO', 'Arrendatario')], max_length=50),
        ),
    ]
