# Generated by Django 5.1.3 on 2024-12-01 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0003_remove_inmueble_user_inmueble_nombre_inmueble_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='region',
            field=models.ForeignKey(default=19, on_delete=django.db.models.deletion.CASCADE, to='gestion_inmuebles.region'),
            preserve_default=False,
        ),
    ]
