# Generated by Django 5.1.3 on 2024-11-21 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0003_alter_usuario_tipo_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
