# Generated by Django 5.1.3 on 2024-11-22 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_inmuebles', '0006_comuna_region_alter_inmueble_comuna_comuna_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('P', 'Propietario'), ('A', 'Arrendatario')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='nombre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_inmuebles.usuario'),
        ),
        migrations.AlterField(
            model_name='inmueble',
            name='tipo_inmueble',
            field=models.CharField(choices=[('C', 'Casa'), ('D', 'Departamento'), ('P', 'Parcela')], default='C', max_length=1),
        ),
    ]
